steps:
- name: gcr.io/${PROJECT_ID}/hugo
- name: gcr.io/${PROJECT_ID}/firebase
  args:
   - deploy
   - --project
   - site-ce15d
  secretEnv:
   - FIREBASE_TOKEN
secrets:

  - kmsKeyName: projects/site-ce15d/locations/global/keyRings/build/cryptoKeys/firebase-deploy
    secretEnv:
      FIREBASE_TOKEN: CiQACY+5jyfwwWfqywvR0s4PWxKLqlQyHcyeE+X3HIsYCs4vjNESawA67de0/pmIBkEqIS2DrKvDMd1SFLUKePQfsnZ8ac8Lgqai5Ro5j/OBWfiMXzSKf6BlQSIPTEr3VD6KyOJ7vaW72/y5IpYGKtD1O59FovzFy0iWfN1aNLBtHI1som7tzHYc7WSM6JgWDkEm
